version: "3.8"

# Include all required services configuration
# Ensure a few things are modified:
# 1. ENV vars
# 2. Volume mounts (for where you would like volumes mounted on your host)
# 3. Decide if you would like to mount /config on each service so you can keep a copy on your host of the config and make changes manually if necessary (outside of container)

services:
  # NOTE: Make sure that libraries are set to /tv and /movies in configuration
  jellyfin:
    image: linuxserver/jellyfin:10.8.13
    hostname: jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - PublishedServerUrl="https://jelly.media.sykesdev.ca"
      - UMASK=022 #optional
    volumes:
      - /cfgdata/jellyfin:/config # Jellyfin config / settings
      - /mnt/jellyfin/tv:/data/tvshows # TV Shows location
      - /mnt/jellyfin/movies:/data/movies # Movies location
    ports:
      - 7359:7359/udp # Discovery on network
      - 1900:1900/udp # Discover on network by DNLA and clients
    # devices:
    #   - /dev/dri:/dev/dri # Remove this if you do not want to use INTEL GPU for hardware excellerated transcoding
    networks:
      - docker-server-tools_server-tools
  # NOTE: Make sure to set download directory to /downloads
  deluge:
    image: linuxserver/deluge:version-2.1.1-r10
    hostname: deluge
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - UMASK=022 # optional
      - DELUGE_LOGLEVEL=error # optional
    volumes:
      - /cfgdata/deluge:/config # Change path for volume mount
      - /mnt/jellyfin/downloads:/downloads # Change path for volume mount
    ports:
      - 127.0.0.1:8112:8112
    networks:
      - docker-server-tools_server-tools
  # NOTE: With Sonarr, when setting up downloader, make sure ip address is "deluge:8112"
  sonarr:
    image: linuxserver/sonarr:4.0.4
    hostname: sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - UMASK=022 # optional
    volumes:
      - /cfgdata/sonarr:/config # Change path for volume mount
      - /mnt/jellyfin/tv:/tv # Change path for volume mount
      - /mnt/jellyfin/downloads:/downloads # Change path for volume mount
    ports:
      - 127.0.0.1:8989:8989
    networks:
      - docker-server-tools_server-tools
  # NOTE: Similar to Sonarr, when setting up downloader make sure to enter "deluge:8112" for the host and port respectively
  radarr:
    image: linuxserver/radarr:5.4.6
    hostname: radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - UMASK=022 #optional
    volumes:
      - /cfgdata/radarr:/config # Change path for volume mount
      - /mnt/jellyfin/movies:/movies # Change path for volume mount
      - /mnt/jellyfin/downloads:/downloads # Change path for volume mount
    ports:
      - 127.0.0.1:7878:7878
    networks:
      - docker-server-tools_server-tools
  bazarr:
    image: linuxserver/bazarr:version-v1.4.2
    hostname: bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - UMASK=022 #optional
    volumes:
      - /cfgdata/bazarr:/config
      - /mnt/jellyfin/movies:/movies #optional
      - /mnt/jellyfin/tv:/tv #optional
    ports:
      - 127.0.0.1:6767:6767
  prowlarr:
    image: linuxserver/prowlarr:1.16.2
    hostname: prowlarr
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
    volumes:
      - /cfgdata/prowlarr:/config
    ports:
      - 127.0.0.1:9696:9696
  # NOTE: With Jackett, ensure blackhole directory is setup at /downloads
  # Also: Ensure trackers are setup from config
  jackett:
    image: linuxserver/jackett:0.20.1406
    hostname: jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - AUTO_UPDATE=true # optional
    volumes:
      - /cfgdata/jackett:/config # Change path for volume mount
      - /mnt/jellyfin/downloads:/downloads # Change path for volume mount
    ports:
      - 127.0.0.1:9117:9117
    networks:
      - docker-server-tools_server-tools
  # CloudFlare Solver
  flaresolverr:
    image: flaresolverr/flaresolverr:v2.2.6
    hostname: flaresolverr
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New York
    networks:
      - docker-server-tools_server-tools

networks:
  # Include the below if integrating with docker-full-media-server project (contains the nginx config)
  docker-server-tools_server-tools:
    external: true
