name: test-compose

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Run Docker-Compose
        run: |
          docker-compose up -d
      - name: Verify servies are running properly
        run: |
          docker-compose ps
          docker ps -a