name: test-compose

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Run Docker-Compose
        run: |
          docker-compose up -d
      - name: Verify servies are running properly
        run: |
          docker-compose ps
          docker ps -a
      - name: Test connectivity (all services)
        run: |
          # Provide some extra time for services to be ready
          sleep 5
          docker run --network docker-full-media-server_media-server-network curlimages/curl curl webserver:80 > /dev/null
          docker run --network docker-full-media-server_media-server-network curlimages/curl curl ombi:3579 > /dev/null
          docker run --network docker-full-media-server_media-server-network curlimages/curl curl deluge:8112 > /dev/null
          docker run --network docker-full-media-server_media-server-network curlimages/curl curl sonarr:8989 > /dev/null
          docker run --network docker-full-media-server_media-server-network curlimages/curl curl radarr:7878 > /dev/null
          docker run --network docker-full-media-server_media-server-network curlimages/curl curl jackett:9117 > /dev/null